# model_name: sentence-transformers/all-mpnet-base-v2
# model_name: vinai/bertweet-base
model_name: vinai/bertweet-base
# model_name: bert-base-cased
# checkpoint_name:
soft_labels: false
class_weight: false
freeze_encoder: false
hidden_dim: 256
dropout_p: 0.1

# Training params
learning_rate: 0.000025
# learning_rate: 0.00008
# learning_rate: 0.00005
max_epochs: 100
accumulate_grad_batches: 1
stopping_patience: 3
warmup_ratio: 0.1
# warmup_ratio: 0.01

# Metrics
logs_dir: tb_logs
logs_name: classifier

# Data params
train_data: data/tweets/train_master.csv
test_data: data/tweets/test_master.csv
all_data: data/tweets/all_tweets.csv
batch_size: 64

global_seed: 42
